"""empty message

Revision ID: c907aa22355f
Revises: 
Create Date: 2024-11-30 14:19:51.805396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c907aa22355f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('key_word', sa.String(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('button_name', sa.String(), nullable=False),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('key_word')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rename_event', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feed', sa.Integer(), nullable=False),
    sa.Column('play', sa.Integer(), nullable=False),
    sa.Column('speak', sa.Integer(), nullable=False),
    sa.Column('sleep', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_word', sa.String(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_word'], ['tasks.key_word'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tasks')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
