"""add upgrades in users

Revision ID: f509440fe072
Revises: d566ef386436
Create Date: 2024-12-02 02:35:22.396430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f509440fe072'
down_revision: Union[str, None] = 'd566ef386436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upgrades', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upgrades')
    # ### end Alembic commands ###
